name: Python Script Workflow
run-name: ${{ github.actor }} is learning GitHub Actions with a Python example
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v4
            
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies and click for error with black
      run: pip install -r requirements/requirements.txt && pip install --upgrade click==8.0.2
    
    - name: Lint with Flake8
      run: flake8 .
    
    - name: Format code with Black
      run: black .
    
    - name: Run Pytest
      run: pytest
    
    - name: Run Python script
      run: python main.py

    - name: Lint, Format, and Test (run together )
      run: flake8 . && black . && pytest . && python main.py
